# Generated by Django 5.0.6 on 2024-05-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.PositiveIntegerField()),
                ('hash', models.CharField(max_length=100000000000000000000000)),
            ],
        ),
    ]
